### PR TITLE
Update run script

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Updated the run script to the latest version. Added a serve endpoint.

## QA
- Run `./run clean` and check there are no errors
- Run `./run build` and check there are no errors
- Run `./run`
- Check the site looks ok
- Run `./run test` and see it passes

### CODE REVIEW

**Comment by MeltySnow** [comment]
Upon running `./run build` the following error occurred:

image

**Comment by anthonydillon** [comment]
@nottrobin any idea? ^

**Comment by nottrobin** [comment]
> I had the same problem and I solved it by removing a space in the name of a folder from my personal path
https://github.com/tmm1/http_parser.rb/issues/47#issuecomment-454397300

@MeltySnow are there spaces in your folder name?

**Comment by nottrobin** [comment]
@MeltySnow ah yeah - `/home/Owen 1`. Is it possible to try running it from a location without a space in the path anywhere?

**Pull request merged**
