### PR TITLE
Build new homepage

### PR DESCRIPTION
**Pull request by anthonydillon**
Update the homepage to match the copy doc and new design.

## QA
- Run `./run`
- Open http://0.0.0.0:8026/
- Check the content matches [the copy doc](https://docs.google.com/document/d/1uI5hsuhe5VUpFSSiQas6FVB2F7RhlbNXcr5Pvr_Lm2c/edit#)
- Check it matches [the design](https://user-images.githubusercontent.com/9105999/56364510-9fa0d200-61e6-11e9-8e30-9434a9a2e8ef.png)
- Check on different screens sizes

## Screenshot
Screenshot_2019-04-23 Multipass - Orchestrates virtual Ubuntu instancess

Fixes https://github.com/canonical-web-and-design/multipass.run/issues/17
Fixes https://github.com/canonical-web-and-design/multipass.run/issues/13

### CODE REVIEW

**Comment by anthonydillon** [comment]
@spencerbygraves all addressed

**Comment by pmahnke** [comment]
for the Get started section... how about

image


```
<section class="p-strip">
  <div class="row">
    <div class="col-12">
      <h2 style="font-weight: 100;">Get started</h2>
      <p>Multipass is available for <a href="/install#macOS">macOS</a> and <a href="/install#windows">Windows</a>, and the many <a href="/install#snap">Linux distributions</a> that support <a href="https://snapcraft.io/" class="p-link--external">snaps</a>.</p>
    </div>
  </div>
  <div class="row p-divider u-equal-height">
    <div class="mobile-col-2 tablet-col-2 col-2">
      <img src="https://assets.ubuntu.com/v1/95b929d4-logo-ubuntu.png" alt="Ubuntu">
    </div>
    <div class="mobile-col-2 tablet-col-2 col-2">
      <img src="https://assets.ubuntu.com/v1/afee3c85-logo-MacOS.png" alt="MacOS">
    </div>
    <div class="mobile-col-2 tablet-col-2 col-2 u-first-col--small">
      <img src="https://assets.ubuntu.com/v1/9522d08d-logo-windows.png" alt="Windows">
    </div>
    <div class="mobile-col-2 tablet-col-2 col-2 u-first-col--medium">
      <img src="https://assets.ubuntu.com/v1/f7f680fb-debian.png" alt="Debian">
    </div>
    <div class="mobile-col-2 tablet-col-2 col-2 u-first-col--small">
      <img src="https://assets.ubuntu.com/v1/eccf1818-raspberrypi.png" alt="Raspberry Pi">
    </div>
    <div class="mobile-col-2 tablet-col-2 col-2 p-divider__block u-vertically-center">
      <a class="p-link--external" href="https://docs.snapcraft.io/installing-snapd/6735">See all the distributions that run snapd</a>
    </div>
  </div>
  <div class="row">
    <div class="col-8">
      <p>Once you've installed Multipass, check out <code>multipass find</code> to see what images are available for you and start one via <code>multipass launch</code>. See <code>multipass help</code> for information on all the commands.</p>
      <p class="u-no-margin--bottom"><a href="/install" class="p-button--positive">Install Multipass now</a></p>
    </div>
  </div>
  <div class="row">
    <hr class="p-separator">
  </div>
  <div class="row">
    <div class="col-12">
      <h3 class="p-heading--two" style="font-weight: 100;">Learn more</h3>
    </div>
  </div>
  <div class="row p-divider">
    <div class="col-4 p-divider__block">
      <h4>Documentation</h4>
      <p><a href="https://discourse.ubuntu.com/c/multipass/doc" class="p-link--external">Documentation and guidance on using Multipass</a></p>
    </div>
    <div class="col-4 p-divider__block">
      <h4>Using cloud-init</h4>
      <p><a href="https://blog.ubuntu.com/2018/04/02/using-cloud-init-with-multipass" class="p-link--external">Learn how to use cloud-init with Multipass to customize your instances</a></p>
    </div>
    <div class="col-4 p-divider__block">
      <h4><participate></participate></h4>
      <ul class="p-list">
        <li class="p-list__item">
          <a href="https://webchat.freenode.net/?channels=#multipass" class="p-link--external">Multipass on Freenode</a>
        </li>
        <li class="p-list__item">
          <a href="https://github.com/CanonicalLtd/multipass" class="p-link--external">Multipass on GitHub</a>
        </li>
        <li class="p-list__item">
          <a href="https://discourse.ubuntu.com/c/multipass" class="p-link--external">Multipass on Ubuntu discourse</a>
        </li>
      </ul>
    </div>
  </div>
</section>
```

**Comment by anthonydillon** [comment]
@spencerbygraves good spot, that is actually a Vanilla bug. [Reported the bug](https://github.com/canonical-web-and-design/vanilla-framework/issues/2287)

**Comment by spencerbygraves** [comment]
@anthonydillon please can you replace the Raspberry Pi logo with Fedora.

https://assets.ubuntu.com/v1/f24733d2-fedora.png

Thanks

**Comment by anthonydillon** [comment]
@spencerbygraves done.

**Comment by spencerbygraves** [comment]
@anthonydillon sorry, just noticed that the link is not aligned vertically with the image on small screen and has lost the dividing line:

image

**Comment by anthonydillon** [comment]
@spencerbygraves done, simplified the section.

**Pull request merged**
